;/*FB_PKG_DELIM*/

__d("InstagramAdBrandProfileFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("4282"),s=o("FalcoLoggerInternal").create("instagram_ad_brand_profile",e),u=s;l.default=u}),98);
__d("InstagramAdTimeSpentFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("3553"),s=o("FalcoLoggerInternal").create("instagram_ad_time_spent",e),u=s;l.default=u}),98);
__d("InstagramAdViewabilityFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("3668"),s=o("FalcoLoggerInternal").create("instagram_ad_viewability",e),u=s;l.default=u}),98);
__d("PolarisAdTimeSpentAction",["InstagramAdTimeSpentFalcoEvent","PolarisContainerModuleUtils","PolarisViewpointActionUtils"],(function(t,n,r,o,a,i,l){"use strict";var e=500,s=new Map;function u(t,n){var r=s.get(t);n.percentVisible>=.5&&r==null&&s.set(t,n.snapshotTime);var o=r==null?0:n.snapshotTime-r;return n.state==="exited"&&o>e?(s.delete(t),o):null}function c(e,t,n,a,i){return function(l){var s=u(n,l);s!=null&&r("InstagramAdTimeSpentFalcoEvent").log(function(){var r,l;return{ad_id:n,follow_status:i,m_pk:(r=o("PolarisViewpointActionUtils").getMPKForFeedMedia(e))!=null?r:"",pigeon_reserved_keyword_module:o("PolarisContainerModuleUtils").getContainerModule(t),pk:(l=e.owner)==null?void 0:l.id,source_of_action:o("PolarisContainerModuleUtils").getContainerModule(t),timespent:s,tracking_token:a}})}}function d(e,t,n,a){return function(i){var l=u(n,i);l!=null&&r("InstagramAdTimeSpentFalcoEvent").log(function(){var r;return{ad_id:n,m_pk:(r=o("PolarisViewpointActionUtils").getMPKForClipsMedia(e))!=null?r:"",pigeon_reserved_keyword_module:o("PolarisContainerModuleUtils").getContainerModule(t),pk:e.ownerId,source_of_action:o("PolarisContainerModuleUtils").getContainerModule(t),timespent:l,tracking_token:a}})}}l.makeAdTimeSpentAction=c,l.makeClipsAdTimeSpentAction=d}),98);
__d("PolarisMediaOptionsMenuQuery_instagramRelayOperation",[],(function(t,n,r,o,a,i){a.exports="35894405730150440"}),null);
__d("PolarisSponsoredBlockedElStore",[],(function(t,n,r,o,a,i){"use strict";var e=new Set;function l(t){e.add(t)}function s(t){return e.has(t)}function u(t){return e.delete(t)}function c(){return e.size>0}i.m=l,i.c=s,i.d=u,i.b=c}),66);
__d("PolarisSponsoredElDisplayMonitor",["clearTimeout","cometGHLContentDisplayCheck","setTimeoutCometLoggingPri"],(function(t,n,r,o,a,i,l){"use strict";var e=new Set,s=1e3,u=null,c=function(n){return e.has(n)||e.add(n),u===null&&d(),{dispose:function(){e.delete(n),e.size===0&&(r("clearTimeout")(u),u=null)}}},d=function(){e.forEach(function(e,t){var n=t.onLogBlockCallback,o=t.startTime,a=t.targetRef,i=a.current;if(i!=null){var l=r("cometGHLContentDisplayCheck")(i);if(!l){var s=Date.now()-o;n(s)}}}),u=r("setTimeoutCometLoggingPri")(d,s)};l.m=c}),98);
__d("PolarisStoriesV3AdsPoolAdState",["$InternalEnum"],(function(t,n,r,o,a,i){"use strict";var e=n("$InternalEnum").Mirrored(["Hidden","Injected","Pool","Seen"]),l=e;i.default=l}),66);
__d("PolarisStoriesV3UnseenWearablesMediaStore",[],(function(t,n,r,o,a,i){"use strict";var e=new Set;function l(t){e.add(t)}function s(t){for(var n of t)if(!e.has(n))return n;return null}i.markWearablesMediaIdAsSeen=l,i.getFirstUnseenId=s}),66);
__d("PolarisStoryStrings",["fbt"],(function(t,n,r,o,a,i,l,s){"use strict";function e(e){return s._(/*BTDS*/"Reply to {username}...",[s._param("username",e)])}function u(e){return s._(/*BTDS*/"Story by {username}, not seen",[s._param("username",e)])}function c(e){return s._(/*BTDS*/"Story by {username}, seen",[s._param("username",e)])}l.directReplyPlaceholder=e,l.unseenStoryTrayItemAriaLabel=u,l.seenStoryTrayItemAriaLabel=c}),226);
__d("getPolarisStoriesV3IsReelSeen_reel.graphql",[],(function(t,n,r,o,a,i){"use strict";var e={kind:"InlineDataFragment",name:"getPolarisStoriesV3IsReelSeen_reel"};a.exports=e}),null);
__d("getPolarisStoriesV3IsReelSeen",["CometRelay","getPolarisStoriesV3IsReelSeen_reel.graphql"],(function(t,n,r,o,a,i,l){"use strict";var e;function s(t){var r,a,i=o("CometRelay").readInlineData(e!==void 0?e:e=n("getPolarisStoriesV3IsReelSeen_reel.graphql"),t),l=Number((r=i.latest_reel_media)!=null?r:0),s=Number((a=i.seen)!=null?a:0);return i.muted===!0||s>=l}l.default=s}),98);
__d("usePolarisDashInfo_media.graphql",[],(function(t,n,r,o,a,i){"use strict";var e={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"usePolarisDashInfo_media",selections:[{alias:null,args:null,kind:"ScalarField",name:"is_dash_eligible",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"number_of_qualities",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"video_dash_manifest",storageKey:null}],type:"XDTMediaDict",abstractKey:null};a.exports=e}),null);
__d("usePolarisDashInfo",["CometRelay","react","react-compiler-runtime","usePolarisDashInfo_media.graphql"],(function(t,n,r,o,a,i,l){"use strict";var e,s,u=(s||(s=o("react"))).useMemo;function c(t){var r=o("react-compiler-runtime").c(4),a=o("CometRelay").useFragment(e!==void 0?e:e=n("usePolarisDashInfo_media.graphql"),t),i=a.is_dash_eligible===1,l;return r[0]!==a.number_of_qualities||r[1]!==a.video_dash_manifest||r[2]!==i?(l={isDashEligible:i,numberOfQualities:a.number_of_qualities,videoDashManifest:a.video_dash_manifest},r[0]=a.number_of_qualities,r[1]=a.video_dash_manifest,r[2]=i,r[3]=l):l=r[3],l}l.default=c}),98);
__d("usePolarisSponsoredElTracker",["IgWebSwankFalcoEvent","PolarisSponsoredBlockedElStore","PolarisSponsoredElDisplayMonitor","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useCallback,c=s.useEffect,d=s.useRef;function m(e){var t=o("react-compiler-runtime").c(13),n=e.mediaType,a=e.position,i=e.postId,l=e.trackingToken,s=d(null),u=d(!1),m;t[0]!==n||t[1]!==a||t[2]!==l?(m=function(t){if(!u.current){u.current=!0,r("IgWebSwankFalcoEvent").log(function(){return{en:String(0),hd:String(t),mt:String(n),sli:String(a),tt:l}});var e=s.current;e!==null&&o("PolarisSponsoredBlockedElStore").m(e)}},t[0]=n,t[1]=a,t[2]=l,t[3]=m):m=t[3];var p=m,_;t[4]===Symbol.for("react.memo_cache_sentinel")?(_=function(){var e=s.current;return(function(){e&&o("PolarisSponsoredBlockedElStore").d(e)})},t[4]=_):_=t[4];var f;t[5]!==a||t[6]!==i?(f=[s,a,i],t[5]=a,t[6]=i,t[7]=f):f=t[7],c(_,f);var g;t[8]!==p?(g=function(){var e=null,t=Date.now();if(s!==null&&u.current!==!0)return e=o("PolarisSponsoredElDisplayMonitor").m({onLogBlockCallback:p,startTime:t,targetRef:s}),(function(){e&&e.dispose()})},t[8]=p,t[9]=g):g=t[9];var h;return t[10]!==p||t[11]!==i?(h=[s,i,u,p],t[10]=p,t[11]=i,t[12]=h):h=t[12],c(g,h),s}l.default=m}),98);
__d("usePolarisSponsoredPostProfileClickLogger",["IGNavChain","InstagramAdBrandProfileFalcoEvent","InstagramODS","InstagramWebAdEventsAuditFalcoEvent","PolarisContainerModuleUtils","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useCallback;function u(e){var t=o("react-compiler-runtime").c(9),n=e.adId,a=e.adTrackingToken,i=e.analyticsContext,l=e.followStatus,s=e.mpk,u=e.postMediaType,c=e.postOwnerId,d=e.socialContext,m;return t[0]!==n||t[1]!==a||t[2]!==i||t[3]!==l||t[4]!==s||t[5]!==u||t[6]!==c||t[7]!==(d==null?void 0:d.social_context_type)?(m=function(){var e,t=o("PolarisContainerModuleUtils").getContainerModule(i);if(!(n==null||a==null)){var m={a_pk:c,ad_id:n,follow_status:l,m_pk:s,m_t:u,nav_chain:(e=r("IGNavChain").getInstance())==null?void 0:e.getNavChainForSend(),pigeon_reserved_keyword_module:t,source_of_action:t,tracking_token:a};r("InstagramWebAdEventsAuditFalcoEvent").log(function(){return{client_token:a,event:"profile_click",social_context_type:d==null?void 0:d.social_context_type}}),r("InstagramODS").incr("web.ads.feed.profile.click"),r("InstagramAdBrandProfileFalcoEvent").log(function(){return m})}},t[0]=n,t[1]=a,t[2]=i,t[3]=l,t[4]=s,t[5]=u,t[6]=c,t[7]=d==null?void 0:d.social_context_type,t[8]=m):m=t[8],d==null||d.social_context_type,m}l.default=u}),98);